### ISSUE TITLE
Lint scripts with ShellCheck

### ISSUE THREAD

**Issue by weak-head** [weak-head/m4b-maker#9]
### Description

Introduce GitHub action to lint the scripts using [ShellCheck](https://www.shellcheck.net/).

### Example

Below is an example of such action:

```yaml
name: Verify Bash Script

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint Bash Scripts
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install ShellCheck
      run: sudo apt-get install -y shellcheck

    - name: Run ShellCheck
      run: |
        # Find all .sh files and lint them
        find . -type f -name "*.sh" -exec shellcheck {} +

  test:
    name: Test Bash Scripts
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Tests
      run: |
        # Give execute permission to all .sh files
        find . -type f -name "*.sh" -exec chmod +x {} +

        # Run the scripts (adjust arguments as necessary)
        for script in $(find . -type f -name "*.sh"); do
          echo "Testing $script"
          bash "$script" || exit 1
        done
```
